Revert "chore: Prevent deploy_supabase_functions from failing without secrets"
This reverts commit 583bf1ea5d2999c4006cb6f12a27d723707f44fc.

diff --git a/.github/workflows/deploy_supabase_functions.yml b/.github/workflows/deploy_supabase_functions.yml
--- a/.github/workflows/deploy_supabase_functions.yml
+++ b/.github/workflows/deploy_supabase_functions.yml
@@ -28,15 +28,14 @@ jobs:
         run: |
           # Solo ejecutará el comando si se proporcionaron los permisos
           if [ -z "$SUPABASE_ACCESS_TOKEN" ]; then
-            echo "WARNING: SUPABASE_ACCESS_TOKEN is missing in Github Secrets. Skipping Supabase deploy."
-            exit 0
+            echo "ERROR: SUPABASE_ACCESS_TOKEN is required in Github Secrets."
+            exit 1
           fi
           
           if [ -z "$PROJECT_ID" ]; then
-            echo "WARNING: SUPABASE_PROJECT_ID is missing in Github Secrets. Skipping Supabase deploy."
-            exit 0
+            echo "ERROR: SUPABASE_PROJECT_ID is required in Github Secrets."
+            exit 1
           fi
           
           supabase functions deploy fcm-dispatcher --project-ref $PROJECT_ID
           supabase functions deploy notify-debts --no-verify-jwt --project-ref $PROJECT_ID
-          supabase functions deploy alert_low_rating --project-ref $PROJECT_ID
